package com.backend.digitalhouse.coworking.util;

import java.util.Arrays;
import java.util.List;

public enum Permission {

    SAVE_ONE_TIPOSALA,
    SEARCH_ONE_TIPOSALA,
    UPDATE_ONE_TIPOSALA,
    DELETE_ONE_TIPOSALA,

    SAVE_ONE_SALA,
    SEARCH_ONE_SALA,
    UPDATE_ONE_SALA,
    DELETE_ONE_SALA,

    READ_ALL_IMAGENES,
    SAVE_ONE_IMAGEN,
    SEARCH_ONE_IMAGEN,
    UPDATE_ONE_IMAGEN,
    DELETE_ONE_IMAGEN,


    READ_ALL_RESERVAS,
    SAVE_ONE_RESERVA,
    SEARCH_ONE_RESERVA,
    UPDATE_ONE_RESERVA,
    DELETE_ONE_RESERVA,

    SAVE_ONE_SERVICIO,
    SEARCH_ONE_SERVICIO,
    UPDATE_ONE_SERVICIO,
    DELETE_ONE_SERVICIO,

    READ_ALL_SEVICIOSSSALAS,
    SAVE_ONE_SERVICIOSALA,
    SEARCH_ONE_SERVICIOSALA,
    UPDATE_ONE_SERVICIOSALA,
    DELETE_ONE_SERVICIOSALA,

    READ_ALL_USUARIOS,
    SEARCH_ONE_USUARIO,

    READ_ALL_TIPOSIDENTIFICACION,
    SAVE_ONE_TIPOIDENTIFICACION,
    SEARCH_ONE_TIPOIDENTIFICACION,
    UPDATE_ONE_TIPOIDENTIFICACION,
    DELETE_ONE_TIPOIDENTIFICACION,

    READ_ALL_ROLES,
    SAVE_ONE_ROL,
    SEARCH_ONE_ROL,
    UPDATE_ONE_ROL,
    DELETE_ONE_ROL
    ;

}